// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAelk79agiDNeExRPL76T8_In9INRlTQlg',
    appId: '1:52952795499:web:e03a35a520c65fac03a42e',
    messagingSenderId: '52952795499',
    projectId: 'modul3mobile-b65b2',
    authDomain: 'modul3mobile-b65b2.firebaseapp.com',
    storageBucket: 'modul3mobile-b65b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcMaouNRsehWDpBvLt1HtMwXjZ32d9z6M',
    appId: '1:52952795499:android:37fa86186b2ac6a603a42e',
    messagingSenderId: '52952795499',
    projectId: 'modul3mobile-b65b2',
    storageBucket: 'modul3mobile-b65b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB43595cj6a2yn-D48mAqX6X6b9Rlz5HV0',
    appId: '1:52952795499:ios:fdfae439b406363c03a42e',
    messagingSenderId: '52952795499',
    projectId: 'modul3mobile-b65b2',
    storageBucket: 'modul3mobile-b65b2.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB43595cj6a2yn-D48mAqX6X6b9Rlz5HV0',
    appId: '1:52952795499:ios:fdfae439b406363c03a42e',
    messagingSenderId: '52952795499',
    projectId: 'modul3mobile-b65b2',
    storageBucket: 'modul3mobile-b65b2.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAelk79agiDNeExRPL76T8_In9INRlTQlg',
    appId: '1:52952795499:web:92f095db88dd1b9603a42e',
    messagingSenderId: '52952795499',
    projectId: 'modul3mobile-b65b2',
    authDomain: 'modul3mobile-b65b2.firebaseapp.com',
    storageBucket: 'modul3mobile-b65b2.appspot.com',
  );
}
